# Generated by Django 4.0.10 on 2023-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('whatsapp', models.BooleanField(default=False)),
            ],
        ),
    ]
